/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.datamarketplace.ui;

import com.mycompany.datamarketplace.datamodels.feature.survey.SurveyQuestions;
import com.mycompany.datamarketplace.datamodels.university.Professor;
import com.mycompany.datamarketplace.datamodels.community.Developer;

import java.awt.CardLayout;
import javax.swing.JSplitPane;

/**
 *
 * @author Admin
 */
public class DeveloperScreen extends javax.swing.JPanel {

    /**
     * Creates new form StudentScreen
     */
    
    JSplitPane splitPane;
    AvailableSurveyList availableSurvey;
    SurveyCreatingPanel createNewSurvey;
    SurveyQuestions selSurveyData;
    RewardsPanel rewards;
    SupportPane supportRequest;
    AvailableBetaTestingList betaTestingList;
    CreateBetaTestingPanel createBetaTests;
    CardLayout layout;
    Developer developerObj;
    
    int selectedSurveyIndex;
    
    public DeveloperScreen(JSplitPane splitPane, Developer developerObj) {
        initComponents();
        this.splitPane = splitPane;
        availableSurvey = new AvailableSurveyList(developerObj, splitPane);
        createNewSurvey = new SurveyCreatingPanel(developerObj);
        rewards = new RewardsPanel();
        supportRequest = new SupportPane();
        betaTestingList = new AvailableBetaTestingList();
        createBetaTests = new CreateBetaTestingPanel();
        
        loadDeveloperDetails(developerObj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeveloperPanel = new javax.swing.JTabbedPane();
        Profile = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        userNameLabel1 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        userNameLabel2 = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        userNameLabel3 = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phNoLabel = new javax.swing.JLabel();
        phoneNumberTxt = new javax.swing.JTextField();
        genderTxt = new javax.swing.JTextField();
        universityLabel = new javax.swing.JLabel();
        communityNameTxt = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        communityIdTxt = new javax.swing.JTextField();
        CreateSurvey = new javax.swing.JPanel();
        TakeSurvey = new javax.swing.JPanel();
        CreateBeta = new javax.swing.JPanel();
        BetaTesting = new javax.swing.JPanel();
        Rewards = new javax.swing.JPanel();
        Support = new javax.swing.JPanel();

        DeveloperPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeveloperPanelMouseClicked(evt);
            }
        });

        Profile.setLayout(new java.awt.CardLayout());

        userNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        userNameLabel.setText("First Name:");

        firstNameTxt.setEditable(false);

        userNameLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        userNameLabel1.setText("Email:");

        emailTxt.setEditable(false);

        userNameLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        userNameLabel2.setText("Age:");

        ageTxt.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Password:");

        passwordTxt.setEditable(false);
        passwordTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        userNameLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        userNameLabel3.setText("Last Name:");

        lastNameTxt.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Gender:");

        phNoLabel.setText("Phone Number:");

        phoneNumberTxt.setEditable(false);

        genderTxt.setEditable(false);

        universityLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        universityLabel.setText("Community Name:");

        communityNameTxt.setEditable(false);
        communityNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityNameTxtActionPerformed(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        idLabel.setText("Community ID:");

        communityIdTxt.setEditable(false);
        communityIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityIdTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameLabel3)
                            .addComponent(userNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(userNameLabel2)
                            .addComponent(phNoLabel)
                            .addComponent(jLabel2)
                            .addComponent(userNameLabel))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ageTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passwordTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(genderTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(phoneNumberTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(universityLabel)
                            .addComponent(idLabel))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(communityIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(communityNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(genderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phNoLabel)
                    .addComponent(phoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(universityLabel)
                    .addComponent(communityNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(communityIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        Profile.add(jPanel1, "card2");

        DeveloperPanel.addTab("Profile", Profile);

        CreateSurvey.setLayout(new java.awt.CardLayout());
        DeveloperPanel.addTab("Create Survey", CreateSurvey);

        TakeSurvey.setLayout(new java.awt.CardLayout());
        DeveloperPanel.addTab("Take Survey", TakeSurvey);

        CreateBeta.setLayout(new java.awt.CardLayout());
        DeveloperPanel.addTab("Create Beta Testing", CreateBeta);

        BetaTesting.setLayout(new java.awt.CardLayout());
        DeveloperPanel.addTab("Beta Testing", BetaTesting);

        Rewards.setLayout(new java.awt.CardLayout());
        DeveloperPanel.addTab("Rewards", Rewards);

        Support.setLayout(new java.awt.CardLayout());
        DeveloperPanel.addTab("Support", Support);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeveloperPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeveloperPanel)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeveloperPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeveloperPanelMouseClicked
        // TODO add your handling code here:
        CreateSurvey.add("Create Survey",createNewSurvey); 
        layout = (CardLayout) CreateSurvey.getLayout();
        layout.next(CreateSurvey);
        
        TakeSurvey.add("Take Survey",availableSurvey); 
        layout = (CardLayout) TakeSurvey.getLayout();
        layout.next(TakeSurvey);
        
        CreateBeta.add("Create Beta Testing", createBetaTests);
        layout = (CardLayout) CreateBeta.getLayout();
        layout.next(CreateBeta);
        
        BetaTesting.add("Beta Testing", betaTestingList);
        layout = (CardLayout) BetaTesting.getLayout();
        layout.next(BetaTesting);
        
        Rewards.add("Rewards",rewards); 
        layout = (CardLayout) Rewards.getLayout();
        layout.next(Rewards);
        
        Support.add("Support", supportRequest);
        layout = (CardLayout) Support.getLayout();
        layout.next(Support);
    }//GEN-LAST:event_DeveloperPanelMouseClicked

    private void communityNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_communityNameTxtActionPerformed

    private void communityIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_communityIdTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BetaTesting;
    private javax.swing.JPanel CreateBeta;
    private javax.swing.JPanel CreateSurvey;
    private javax.swing.JTabbedPane DeveloperPanel;
    private javax.swing.JPanel Profile;
    private javax.swing.JPanel Rewards;
    private javax.swing.JPanel Support;
    private javax.swing.JPanel TakeSurvey;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JTextField communityIdTxt;
    private javax.swing.JTextField communityNameTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JTextField genderTxt;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JLabel phNoLabel;
    private javax.swing.JTextField phoneNumberTxt;
    private javax.swing.JLabel universityLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userNameLabel1;
    private javax.swing.JLabel userNameLabel2;
    private javax.swing.JLabel userNameLabel3;
    // End of variables declaration//GEN-END:variables
private void loadDeveloperDetails(Developer developerObj) {
        firstNameTxt.setText(developerObj.getFirstName());
        lastNameTxt.setText(developerObj.getLastName());
        emailTxt.setText(developerObj.getEmail());
        ageTxt.setText(String.valueOf(developerObj.getAge()));
        genderTxt.setText(developerObj.getGender());
        phoneNumberTxt.setText(String.valueOf(developerObj.getPhoneNumber()));
        communityNameTxt.setText(developerObj.getCommunityName());
        communityIdTxt.setText(developerObj.getSocialId());
    }
}
